# safelist
#branches:
#  only:
#    - master
language: bash

services:
  - docker

before_install:
  - docker pull hubbitus/latex
script:
  - docker run --rm  -it -v $(pwd):/source hubbitus/latex bash -c 'pdflatex -synctex=1 -interaction=nonstopmode cv.tex; pdflatex -synctex=1 -interaction=nonstopmode cvRus.tex; exit 0'

deploy:
  - provider: releases
    api_key: $TOKEN
    file: "cv.pdf"
    skip_cleanup: true
    on:
      branch: master
  - provider: releases
    api_key: $TOKEN
    file: "cvRus.pdf"
    skip_cleanup: true
    on:
      branch: master